# -*- coding: utf-8 -*-
"""Pratica_capitulo_05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m-X7seG9kTH7oXM5d_c8-x54s_PWf--o
"""



"""VARIÁVES"""

x=x+1   # Erro de variável não definida

x=0
x=x+1

"""COMANDO WHILE"""

n=0              #atribui ZERO para a variável n
while n>0:       #Só entra no loop se a variável n for maior que ZERO, ou seja nunca executará o LOOP
  print(n)
  n=n-1
print('Fim')

n=0               #atribui ZERO para a variável n
while n>=0:       #Só entra no loop se a variável n for maior ou igual a ZERO, executará o LOOP
  print(n)
  n=n-1           #torna o n NEGATIVO , o WHILE será executado uma vez
print('Fim')

n=0               #atribui ZERO para a variável n
while n>=0:       #Só entra no loop se a variável n for maior ou igual a ZERO, executará o LOOP
  print(n)
  n=n+1           #torna o n POSITIVO , o WHILE será infinito
print('Fim')

while True:               #Loop infinito
  linha=input('>')        #Aguarda a digitação
  print(linha)        
  if linha=='parar':
    break                 #Ao ser digitada a palavra 'parar' o comando BREAK para o LOOP
  print(linha)
print('FINALIZADO')

"""ITERAÇÕES COM O COMANDO CONTINUE"""

while True:               #Loop infinito
  linha=input('>')        #Aguarda a digitação
  print(linha)       
  if linha[0]=='#':       #Se o primeiro caracter da digitação for "#"
    continue              #Se o caracter "#" for digitado volta ao começao do WHILE
  if linha =='parar':
    break
  print(linha)
  print('Mais uma iteração')
print('FINALIZADO')

"""COMANDO FOR"""

listaAmigos = ['maria','jose','joaquim','marcia','francisco']
for nomeAmigo in listaAmigos:
  print('Prazer em revê-lo : ',nomeAmigo)
print('FINALIZADO')

"""CONTA E SOMAR"""

contador=0
for item in [12,45,67,89,34,65,23,89]:
  contador=contador+1
print('Contagem de items : ',contador)

soma=0
for item in [12,45,67,89,34,65,23,89]:
  soma=soma+item
print('Soma dos itens : ',soma)

"""MÁXIMO E MÍNIMO"""

maior = None
print('Iniciando a escolha do MAIOR')
for item in [87,90,23,66,12,34,97,56,123]:
  if maior is None or item>maior:
    maior=item
  print('Ainda não terminei : ',item,maior)
print('Maior valor é : ', maior)

menor = None
print('Iniciando a escolha do MENOR')
for item in [87,90,23,66,12,34,97,56,123]:
  if menor is None or item<menor:
    menor=item
  print('Ainda não terminei : ',item,menor)
print('Menor valor é : ', menor)