# -*- coding: utf-8 -*-
"""Pratica_Capitulo_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Edhgyqt-sjy1P2LPOjzSBu7rI0NCXXEw

FUNDAMENTO DE PYTHON - UNIDADE-04
"""

##FUNÇÕES BUILT-IN  (funções integradas)
print(type(32))
print(type('jose'))
print(type(2.0))

print(max('ola mundo'))  # A letra "u" será a maior, mas se acentuar o "á" será esta
print(min('ola mundo'))  # O menor caracter será o espaço em branco
print(len('ola mundo'))

## CONVERSÃO DE TIPOS
print(int('32'))
print(type(int('32')))
print(int(3.999999))
print(int(-2.333))

print(float(32))
print (float(('3.45678')))

print(type(int('Brasil')))  ##Erro será retornado

## NÚMEROS RANDÔMICOS
## Serão gerados 10 números randômicos entre 0 e 1
## inclui o 0.0 mas não o 1.0
import random
for i in range(10):
  print(random.random())

## Função RANDINT
print(random.randint(1,10))  ##Gera inteiros randômicos entre 1 e 10 inclusive

## Função CHOICE
t = [1,2,3,4,5,6]
print(random.choice(t))  ## Gera números randômicos dentro da lista

## Funções MATEMÁTICAS
import math
print(math)

ratio = 5
decibel = 10 * math.log10(ratio)
print(ratio,decibel)

radiano = 45
print(math.sin(radiano))

grau = 76
radiano = grau /360.0 * 2 * math.pi
print(math.sin(radiano))
print(math.sqrt(2)/2.0)

## FUNÇÕES DEFINIDAS PELO USUÁRIO
## FUNÇÕES VAZIAS : Não possuem valor de retorno

def imprimir_mensagem():
  print('Brasil meu país')
  print('Verás que um filho teu não foge à luta')
  print('Nem temes quem te adora à própria morte')

def imprimir_nome(nome):
  print('Na outra função')
  print(nome)
  print(nome * 4)

##Chamando as funções
print(imprimir_mensagem())
print(imprimir_nome('Brasil  '))

## FUNÇÕES DEFINIDAS PELO USUÁRIO
## FUNÇÕES FÉRTEIS : retornam um valor

def imprimir_mensagem(nome):
  return (nome *4)
def soma(op1,op2):
  return (op1 + op2)

print(imprimir_mensagem(' fortaleza '))

print(soma(3,4))

##CALCULADORA
def calculadora(operacao,op1,op2):
  if operacao =='soma':
    x = op1+op2
  elif operacao =='subtracao':
    x = op1-op2
  elif operacao =='multiplicacao':
    x = op1*op2
  elif operacao =='divisao':
    x = op1 / op2
  else :
    print('operacao inválida')
  return x

print(calculadora('soma',6,8))
print(calculadora('subtracao',16,8))
print(calculadora('multiplicacao',9,7))
print(calculadora('divisao',120,4))