# -*- coding: utf-8 -*-
"""pratica_Capitulo_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3-Z-minCQUwKILl9PSZdPVOgPUf5SRz

FUNDAMENTO DE PYTHON - UNIDADE-03
"""

x=10
y=3
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)
print(x is y)
print(x is not y)

##OBSERVAÇÃO  :  erros de sintaxe
x=20
y=30
print(x=>y)   #correto :  x>=y
print(x=<y)   #correto :  x<=y

## OPERADOR DE COMPARAÇÃO
print(x==10)     ##Não haverá erro de sintaxe, pois é uma comparação

## OPERADOR DE ATRIBUIÇÃO
print(x=10)   ## erro de ARGUMENTO INVÁLIDO para função :   print()

"""OPERADORES LÓGICOS"""

##Qualquer numero diferente de ZERO é considerado TRUE
print('***Lógica AND***')
print(1 and True)
print(True and 81)
print(True and 0)
print(23 and True)
print(17 and True)
print(100 and True)
print(0 and True)   ##zero é FALSO
##---------------------
print('***Lógica OU***')
print('**True**')
print(1 or True)
print(23 or True)
print(17 or True)
print(100 or True)
print(0 or True)
print('**False**')
print(1 or False)
print(23 or False)
print(17 or False)
print(100 or False)
print(0 or False)

print('***AND***')
print(3 and 2)
print(6 and 8)
print(5 and 9)
print(9 and 5)
#---
print('***OR***')
print(3 or 2)
print(6 or 8)
print(5 or 9)
print(9 or 5)

##EXECUÇÃO CONDICIONAL
x=39
if x>0 :
  print('x é positivo')

##EXECUÇÃO ALTERNATIVA
x=38
if x%2==0 :
  print('x é par')
else:
  print('x é impar')

##CONDIÇÕES ENCADEADAS
x=10
y=10
if x<y:
  print('x é menor que y')
elif x>y:
  print('x é maior que y')
else:
  print('x é igual a y')

##CONDIÇÕES ANINHADAS

##CONDIÇÕES ENCADEADAS
x=10
y=710
if x==y:
  print('x é igual a y')
else:
  if x>y:
   print('x é maior que y')
  else:
   print('x é menor y')

##CONDIÇÕES DE EXCEÇÃO
##Sem tratamento de exceção.   Digitando um string será retornado um erro
inp=input('Entre com a temperatura em FAHRENHEIT')
fahr = float(inp)
cel = (fahr - 32.0) * 5.0/9.0
print(cel)

##CONDIÇÕES DE EXCEÇÃO
##Com tratamento de exceção.
inp=input('Entre com a temperatura em FAHRENHEIT :  ')
try:
  fahr = float(inp)
  cel = (fahr - 32.0) * 5.0/9.0
  print(cel)
except:
  print('A entrada deve ser obrigatoriamente numérica')

##PERFIL GUARDIÃO
##Apesar do valor de y=0, provocando um erro na divisão de x por y
##Nenhum erro é retornado.  Como é um AND a primeira sendo falsa não há necessidade
##de avaliar o segundo argumento. Então nenhum erro é retornado pois x=1 e portanto menor que 2
##expresão avaliada :  x>=2
x=1
y=0
print(x>=2 and (x/y)>2)

##PERFIL GUARDIÃO
##Para que a expressão toda seja verdadeira ambas devem ser verdadeira.
##Para x=5, x>=2 é verdadeiro.  A segunda expressão precisará ser avaliada
##Erro de divisão por zero será retornado
x=5
y=0
print(x>=2 and (x/y)>2)