# -*- coding: utf-8 -*-
"""Pratica_Capitulo_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZKX7GNRuF98l6-mAP6RXApoGh3d7Np-c

**VARIÁVEIS, EXPRESSÕE E COMANDOS**
"""

print(4)
print("4")
print(3.2)
print("3.2")
print("primeiro texto")

print(type(4))
print(type("4"))
print(type(3.2))
print(type("3.2"))
print(type("primeiro texto"))

"""**ERRO DE SEMÂNTICA**"""

print(1,000,000,00)    # Erro de semântica se a intenção era escrever o número 1,000,000.00
print(1,000,000.00)    # Erro de semântica
print(f'Número Formatado :  {1000000:,.2f}')
#print(1.000.000)      # Sintaxe inválida
print(1000000)

"""**VARIÁVEIS**"""

mensagem = 'Esta é uma mensagem para a variável'
n=17
pi=3.1415926536
print(mensagem,n,pi)

"""**NOME DE VARIÁVEIS E PALAVRAS CHAVES**"""

2022PrimeiraVariavel = "testando"    # Sintaxe inválida, nome não pode começar com número
email@ = "amarantegba@outlool.com"   # Sintaxe inválida, nome não pode conter caracter especial
class ="Python básico"               # Sintaxe inválida, nome não pode ser uma palavra reservada do PYTHON
meu nome = "amarante"                # não pode conter espaços no nome da variável

pi=3.14
print(Pi)  # O nome da variável é sensível ao caso (case sensitive), a letra P está em letra maiúscula

"""**COMANDOS**"""

print("viva o Brasil")
men = "viva o Brasil"
print(men)
print(1)
x=2
print(x)

"""**OPERADORES E OPERANDOS**"""

minuto=590
minuto/60  #Resultado da divisão é em ponto flutuante
## Truncar o resultado para inteiro
minuto=590
minuto//60

"""**EXPRESSÕES**"""

5
X=5
X+1

"""#soma dois valores
5 + 2 resulta em 7
#subtrai dois valores
5 - 2 resulta em 3
#multiplica dois valores
5 * 2 resulta em 10
#divide dois valores (sem arredondar)
5 / 2 resulta em 2.5
#divide dois valores (arredondando para baixo)
5 // 2 resulta em 2
#resto da divisão
5 % 2 resulta em 1
#exponenciação
5 ** 2 resulta em 25
"""

print(5+2)
print(5-2)
print(5*2)
print(5/2)
print(5//2)
print(5%2)
print(5**2)

"""**ORDEM DAS OPERAÇÕES**"""

## PARÊNTESES
print(2*(3-1))
print((1+1)**(5-2))
minuto=456
print((minuto*100)/60)

## EXPONENCIAÇÃO
print(2**1+1)
print(3*1**3)

## MULTIPLICAÇÃO E DIVISÃO
print(2*3-1)
print(6+4/2)

## OPERADOR MODULAR
print(7//3) #quociente inteiro
print(7%3)  #resto da divisão

## OPERAÇÃO COM CADEIA DE CARACTERES
var_nome=input("Qual o seu nome ? ")  ##Pede a variável na mesma linha
print(var_nome)

##\n
var_nome=input("Qual o seu nome ?\n") ##Pede a variável na linha seguinte
print(var_nome)

## OPERAÇÃO COM NÚMEROS INTEIROS
var_idade=input("Qual a sua idade ? ")  
print(type(var_idade))
print(var_idade+3)    ## Erro, a classe da variável var_idade é string

## OPERAÇÃO COM NÚMEROS INTEIROS
var_idade=int(input("Qual a sua idade ? "))  
print(type(var_idade))
print(var_idade+3)

"""EXERCÍCIOS

1 - Write a program that uses input to prompt a user for their
name and then welcomes them.
"""

nome=input("Digite seu nome :")
print("Seja bem vindo "+nome)

"""2 - Write a program to prompt the user for hours and rate per
hour to compute gross pay.
"""

horas=int(input("Entre com o número de horas : "))
valorHora=float(input("Entre com o valor da hora : "))
print("Valor do Pagamento : ",horas*valorHora)

"""3 - Assume that we execute the following assignment statements:
width = 17
height = 12.0


For each of the following expressions, write the value of the expression and the
type (of the value of the expression).
1. width//2
2. width/2.0
3. height/3
4. 1 + 2 * 5
"""

## Item 3.1
width=17
height=12.0
print(width//2)
print(type(width//2))

##Item 3.2
width=17
height=12.0
print(width/2)
print(type(width/2))

##Item 3.2
width=17
height=12.0
print(height/3)
print(type(height/3))

##Item 3.4
print(1 + 2 * 5)
print(type(1 + 2 * 5))

"""4 - Write a program which prompts the user for a Celsius temperature, 
convert the temperature to Fahrenheit, and print out the converted temperature.
"""

celsius=float(input("Digite a temperatura em graus Celsisu :  "))
fahrenheit= celsius * 1.8 + 32
print(f'Temperatura em Fahrenheit : {round(fahrenheit, 2)}')