# -*- coding: utf-8 -*-
"""PrimeiroCapitulo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udm2ivAJd05tptKwrZ8g7eqrSX5LAUgI

O ZEN DO **PYTHON**
"""

import this

print("Fala Brasil")

"""Console de comandos"""

!python --version

x=6
print(x)
y=x*7
print(y)

"""# **EXERCÍCIOS BÁSICOS**

Escreva um PROGRAMA que armazene o valor 10 em uma variável A e o valor 20 em Uma variável B.
A seguir troque os seus conteúdos fazendo com que o
valor que está em A passe para B e vice-versa. Ao final, escrever os valores que ficaram armazenados
nas variáveis.
"""

x=10
y=20
a=x
x=y
y=a
print(x)
print(y)

"""Escreva um programa para ler um valor (do teclado) e escrever (na tela) o seu antecessor. """

x=int(input("digite um número :  "))
x=x-1
print("antecessor do número   é : ",x)

"""Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a
área do retângulo. 
"""

x=int(input("Digite a base do retângulo :   "))
y=int(input("Digite a altura do retângulo : "))
print("A área do retângulo é : ",x*y)

"""Faça um algoritmo que leia a idade de uma pessoa expressa em anos, meses e dias e escreva a idade
dessa pessoa expressa apenas em dias. Considerar ano com 365 dias e mês com 30 dias.
"""

x=int(input("Digite o número de anos :  "))
y=int(input("Digite o número de meses :  "))
z=int(input("Digite o número de dias :  "))
a = 365 * x
b = 30 * y
print("A idade em número de dias é :  ",a+b+z)

"""O custo de um carro novo ao consumidor é a soma do custo de fábrica com a porcentagem do
distribuidor e dos impostos (aplicados ao custo de fábrica). Supondo que o percentual do distribuidor
seja de 28% e os impostos de 45%, escrever um algoritmo para ler o custo de fábrica de um carro,
calcular e escrever o custo final ao consumidor. 
"""

x=float(input("Digite o custo de fábrica do carro :  "))
y=x*28/100  #Percentual do distribuidor
a=x*45/100  #Impostos
soma=x+y+a
print("O custo final ao consumidor é :  ",soma)

"""Uma revendedora de carros usados paga a seus funcionários vendedores um salário fixo por mês,
mais uma comissão também fixa para cada carro vendido e mais 5% do valor das vendas por ele
efetuadas. Escrever um algoritmo que leia o número de carros por ele vendidos, o valor total de suas
vendas, o salário fixo e o valor que ele recebe por carro vendido. Calcule e escreva o salário final do
vendedor. 
"""

x=int(input("Número de carros vendidos : "))
y=float(input("Valor total das vendas no mês :  "))
z=float(input("Salário Fixo : "))
w=int(input("Percentual por carro vendido : "))
total_por_carro_vendido = x*w/100
adicional_por_venda = y*5/100
valor_recebido= total_por_carro_vendido + adicional_por_venda + z
print("A receber no mês :  ",str(valor_recebido))