# -*- coding: utf-8 -*-
"""PrimeiroCapitulo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1udm2ivAJd05tptKwrZ8g7eqrSX5LAUgI
"""



"""O ZEN DO **PYTHON**"""

import this